name: CI
on: 
  push:
    tags: [v*]
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Run test
        run: |
          npm ci
          npm t
      - name: Setup Clasp
        uses: rmuraix/setup-clasp@044fcab73577c78a9b041b722bb4a4cfb3eb212c
        with:
          clasp-version: 2.4.2
          access-token: ${{ secrets.ACCESS_TOKEN }}
          id-token: ${{ secrets.ID_TOKEN }}
          refresh-token: ${{ secrets.REFRESH_TOKEN }}
          client-id: ${{ secrets.CLIENT_ID }}
          client-secret: ${{ secrets.CLIENT_SECRET }}
          script-id: ${{ secrets.SCRIPT_ID }}
          root-dir: "./src"
      - name: push to gas
        run: clasp push -f
      - name: Codecov
        uses: codecov/codecov-action@v3.1.1
        with: 
          files: coverage/cobertura-coverage.xml
          flags: unittests
          fail_ci_if_error: true
